Bump to version 6.02
flathub/com.vesc_project.VescTool pull request #7
Opened 2024-03-04 21:38 UTC by albfan

2024-03-04 22:31 UTC, hfiguiere commented on com.vesc_project.VescTool.desktop
> +Version=6.02
this is invalid. this is not the app version. has never been.

2024-03-04 22:32 UTC, hfiguiere requested changes
this builds against a runtime that is EOL.

2024-03-04 22:43 UTC, albfan commented
there was some error with code base and 23.08, see #5 but I can upgrade that too

2024-03-04 22:50 UTC, albfan commented
I'm unsure what this line means:

> /usr/lib/gcc/x86_64-unknown-linux-gnu/11.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot open output file QCodeEditor: Is a directory

2024-03-04 23:10 UTC, albfan commented
I think it fails with some errors after upgrade to 23.08. module lzokay is not updated and code is abbandoned: https://github.com/AxioDL/lzokay

2025-02-01 01:17 UTC, albfan commented
For whatever reason version 6.02 do not build, giving up

2025-02-01 01:17 UTC, closed without merging